version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"