version: "3"

services:
  accounts-db:
    image: postgres:latest
    restart: always
    env_file:
      - "postgres.env"
    volumes:
      - .docker-volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend


  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
    depends_on:
      - accounts-db
      - auth
      - tester
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  auth:
    build:
      context: ./src/auth
      dockerfile: ./Dockerfile
    depends_on:
      accounts-db:
        condition: service_healthy
    env_file:
      - "./src/auth/.env"
    environment:
      - DB_HOST=accounts-db
    networks:
      - backend

  tester:
    build:
      context: ./src/tester
      dockerfile: ./Dockerfile
    env_file:
      - "./src/tester/.env"
    networks:
      - backend

networks:
  backend:
    driver: bridge