version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - "postgres.env"
    volumes:
      - .docker-volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: 'nginx:latest'
    ports:
      - "80:80"
    depends_on:
      - database
      - auth
      - tester
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  auth:
    build:
      context: ./auth
      dockerfile: ./Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - "./auth/.env"
    environment:
      - DB_HOST=database

  tester:
    build:
      context: ./tester
      dockerfile: ./Dockerfile
    env_file:
      - "./tester/.env"
    environment:
      - API_GATEWAY=http://nginx:80